CREATE DATABASE av2;
USE av2;
CREATE TABLE tbAlunos(
    ra BIGINT(10) AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(30) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    telefone VARCHAR(255) NOT NULL,
    curso VARCHAR(255) NOT NULL
);